# Generated by Django 3.2.4 on 2021-07-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='thumbs_up',
            new_name='points',
        ),
    ]
