# Generated by Django 3.2.4 on 2021-06-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(blank=True, max_length=12, null=True)),
                ('scenic', models.BooleanField(blank=True, default=False, null=True)),
                ('adult_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('child_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('family_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
