# Generated by Django 3.2.4 on 2021-07-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('description', models.TextField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('size', models.CharField(max_length=6)),
                ('street_address_1', models.CharField(max_length=80)),
                ('street_address_2', models.CharField(blank=True, max_length=80, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('scenic', models.BooleanField(blank=True, default=False, null=True)),
                ('family_friendly', models.BooleanField(blank=True, default=False, null=True)),
                ('adult_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('child_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('family_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('x_map_reference', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('y_map_reference', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_credit', models.CharField(max_length=64)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
