# Generated by Django 3.2.4 on 2021-06-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='size',
            field=models.CharField(max_length=6),
        ),
    ]
