# Generated by Django 3.2.4 on 2021-06-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0002_auto_20210630_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='extra_info',
            field=models.TextField(default=False),
        ),
    ]
