# Generated by Django 3.2.4 on 2021-07-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0002_alter_resort_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='family_friendly',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='image_credit',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='resort',
            name='town_or_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
