# Generated by Django 3.2.4 on 2021-06-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0003_resort_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
