# Generated by Django 3.2.4 on 2021-07-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0003_auto_20210702_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='image_credit',
            field=models.CharField(max_length=64),
        ),
    ]
