# Generated by Django 3.2.4 on 2021-07-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0006_auto_20210702_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='x_map_reference',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='y_map_reference',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
